// Debug script to check model.json structure in detail
const fs = require('fs');
const path = require('path');

console.log('Analyzing model.json structure in detail...');

try {
  const modelPath = path.join(__dirname, 'public', 'calendar_event_classification_model', 'model.json');
  const modelData = JSON.parse(fs.readFileSync(modelPath, 'utf8'));
  
  console.log('Model format:', modelData.format);
  console.log('Generated by:', modelData.generatedBy);
  console.log('Converted by:', modelData.convertedBy);
  
  const layers = modelData.modelTopology.model_config.config.layers;
  console.log('\nTotal layers:', layers.length);
  
  console.log('\nAnalyzing all layers...');
  layers.forEach((layer, index) => {
    console.log(`\nLayer ${index + 1}: ${layer.name} (${layer.class_name})`);
    
    if (layer.class_name === 'InputLayer') {
      console.log('  InputLayer config:');
      console.log('    batchInputShape:', layer.config.batchInputShape);
      console.log('    inputShape:', layer.config.inputShape);
      console.log('    batch_shape:', layer.config.batch_shape);
      console.log('    dtype:', layer.config.dtype);
      console.log('    All config keys:', Object.keys(layer.config));
    }
  });
  
  // Check for any remaining batch_shape references
  const modelString = JSON.stringify(modelData);
  const batchShapeMatches = modelString.match(/batch_shape/g);
  const batchInputShapeMatches = modelString.match(/batchInputShape/g);
  
  console.log('\nString analysis:');
  console.log('batch_shape occurrences:', batchShapeMatches ? batchShapeMatches.length : 0);
  console.log('batchInputShape occurrences:', batchInputShapeMatches ? batchInputShapeMatches.length : 0);
  
} catch (error) {
  console.error('Error analyzing model:', error);
}
